spring:
  datasource:
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      hibernate.ddl-auto: update

  profiles:
    active=@spring:
      profiles:
        active@

server:
    port: 8080



